Generic Client for Android
mattermost/react-native-network-client pull request #17
Opened 2020-12-07 05:34 UTC by shazm

From our conversation earlier - just splitting up these PR's for ease of review.

2020-12-08 00:39 UTC, shazm commented on android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt
> +    fun get(baseUrl: String, options: ReadableMap, promise: Promise){
Ah yup! Will update 👍

2020-12-10 14:55 UTC, enahum requested changes

2020-12-10 14:55 UTC, enahum commented on android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt
> +            promise.reject("Unexpected code $response")
I think you  should reject the promise but include the response even if its not successful so it bubbles up all the way to JS. Same thing with all the other methods

2020-12-16 23:18 UTC, shazm commented on android/src/main/java/com/mattermost/networkclient/GenericClientModule.kt
> +        val body = options.toString().toRequestBody();
Yup - I start handling them here; https://github.com/mattermost/react-native-network-client/pull/19

2020-12-17 06:12 UTC, enahum approved these changes

2020-12-17 06:12 UTC, merged