iOS - Client certificate
mattermost/react-native-network-client pull request #43
Opened 2021-03-03 00:07 UTC by migbot

2021-03-09 20:25 UTC, enahum approved these changes
this looks really good

2021-03-10 21:40 UTC, shazm approved these changes

2021-03-10 22:52 UTC, josephbaylon commented on example/src/utils/index.tsx
> +    const requestAdapterConfiguration = {
@migbot This is already declared as parameter in line 55. This was moved to parameter so that other clients can pass a different value.

2021-03-11 00:17 UTC, josephbaylon commented
@migbot Per our conversation, the app crashes when it attempts to upload

2021-03-11 22:32 UTC, josephbaylon commented on example/src/utils/index.tsx
> +    const origin = `https://${host}`;
@migbot Quick question: should the protocol be `wss` instead of `https` ?

2021-03-11 22:43 UTC, josephbaylon commented
With the latest commit, API client requests for get/put/post/patch/delete/upload now crash as well.

Generic client requests for get/put/post/patch/delete and fast-image API client request work fine.

2021-03-12 21:58 UTC, josephbaylon commented
@migbot I ran the whole suite for regression testing and everything passed. I'll rerun the suite again after you push your self-signed certs fix and approve the PR if everything passes.

2021-03-12 23:29 UTC, josephbaylon approved these changes
LGTM. Regression testing passed. As discussed in chats, I'll test the certificate auth feature after merge to master, once I start creating automated e2e around it.

2021-03-12 23:29 UTC, josephbaylon approved these changes
LGTM. Regression testing passed. As discussed in chats, I'll test the certificate auth feature after merge to master, once I start creating automated e2e around it.

2021-03-16 23:13 UTC, shazm requested changes
Just a minor change which might clean up our type declarations; looks good otherwise! 👍

2021-03-16 23:13 UTC, shazm commented on @types/APIClients.ts
> +declare global {
I actually just had a thought around this - how about we declare `EmitterSubscription` and `NativeModule` as a global type in a `@types/Global.ts`, and that way we can use both of these without needing to import into our actual declarations.

Something like:

```
// @types/Global.ts

import type { NativeModule as NM, EventEmitter as EE } from "react-native";

declare global {
    interface NativeModule extends NM {}
    interface EventEmitter extends EE {}
}
```

This way we can use EventEmitter and NativeModule globally without needing to import the react types, thus not needing to do `declare global { ....` on our types.

2021-03-16 23:13 UTC, shazm commented on @types/NativeAPIClient.ts
> +    enum APIClientEvents {
Same as above - can potentially remove `declare global` here too.

2021-03-17 00:46 UTC, shazm approved these changes

2021-03-17 02:29 UTC, merged