Return appropriate errors/warnings from iOS to JS
mattermost/react-native-network-client pull request #52
Opened 2021-03-19 03:51 UTC by migbot

#### Summary

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31773

2021-03-19 07:33 UTC, enahum requested changes
Apart from my comments, why are the events warnings and not errors? And why do we send the localize message only? Perhaps a code would be good instead of trying to match localized strings if the app wants to handle different UX based on the code.

I can see how MM would use the cert missing "warning" to provide some UI to import the cert as a response

2021-03-19 07:33 UTC, enahum commented on src/APIClient/index.tsx
> +                    Alert.alert("Warning", event.warning, [{ text: "OK" }], {
Why display an alert here? I guess this should be fwd to the applicstion making use of the lib (aka the example app) and let it handle the UX as they see fit

2021-03-19 07:33 UTC, enahum commented on src/WebSocketClient/index.tsx
> +                    Alert.alert("Warning", event.warning, [{ text: "OK" }], {
Same here

2021-03-19 22:19 UTC, shazm commented
> Apart from my comments, why are the events warnings and not errors? And why do we send the localize message only? Perhaps a code would be good instead of trying to match localized strings if the app wants to handle different UX based on the code.
> 
> I can see how MM would use the cert missing "warning" to provide some UI to import the cert as a response

Oh so the thinking was - if there is an "error", the called promise should be rejected and handled accordingly; for a lot of the places we're emitting events we still want the promise to resolve (even if partially) and just return a message / warning to the user. 

The main example is trying to make an API client with a certificate; if there is an issue with the certificate i.e. wrong password, the client should still be created but a warning to the user given, and then the option to add the certificate later to that client.

2021-03-21 00:06 UTC, shazm approved these changes
Looks good to me - just would like to clean up our naming around host/baseUrl/domain.

2021-03-21 19:21 UTC, enahum requested changes
Please add the error codes to the README.md file :)

2021-03-21 19:21 UTC, enahum commented on @types/APIClients.ts
> +    nativeStackIOS?: Array<unknown>;
why the difference?

2021-03-21 19:21 UTC, enahum commented on @types/WebSocketClient.ts
> +    clientErrorEventHandler?: WebSocketClientErrorEventHandler;
bad copy/paste?

2021-03-21 19:21 UTC, enahum commented on src/APIClient/index.tsx
> +                        Alert.alert(
So in case this is unhandled because I don't want need to handle it you are forcing me to get an Alert? I rather remove the else statement

2021-03-21 19:21 UTC, enahum commented on src/WebSocketClient/index.tsx
> +                        Alert.alert(
same here

2021-03-22 17:01 UTC, enahum commented on @types/WebSocketClient.ts
> +    clientErrorEventHandler?: WebSocketClientErrorEventHandler;
Got confused with clientError and WSClientError

2021-03-22 17:21 UTC, enahum commented on @types/APIClients.ts
> +    userInfo?: Record<string, unknown>;
You can read more about it in [this blog post](https://rossbulat.medium.com/typescript-generics-explained-15c6493b510f) I was thinking that each consumer can define the type they expect to get back to make it less error prone

2021-03-22 17:39 UTC, enahum requested changes
Also consider adding a table with a list of error codes and descriptions

2021-03-22 17:39 UTC, enahum commented on README.md
> +There are two cases where errors will be returned by the native code. The first is via rejected promises and the second is via events.
Isn't the second one really using an error callback triggered by the JS side of the lib? I tought only the Lib was listening for the events, maybe I'm wrong?

2021-03-22 17:39 UTC, enahum commented on README.md
> +    userInfo: Object;
Ueah maybe just call this extra. And about domain, is it really needed?

2021-03-22 17:39 UTC, enahum commented on README.md
> +- Keychain specific errors will be in the range -100 to -199
Maybe explain that this are related to client certs

2021-03-22 17:51 UTC, josephbaylon commented
@migbot It seems you're using a code formatter. Can you share that so I can use that locally as well?

2021-03-22 19:37 UTC, josephbaylon commented
@migbot I know this is iOS but getting the following error when building android using `npm run android`

![Screen Shot 2021-03-22 at 12 36 36 PM](https://user-images.githubusercontent.com/487991/112048165-5b718700-8b0b-11eb-9882-35bbd275f720.png)

2021-03-22 21:48 UTC, josephbaylon commented
The issue https://github.com/mattermost/react-native-network-client/pull/52#issuecomment-804341145 looks like it was introduced by https://github.com/mattermost/react-native-network-client/pull/47 and android testing was missed there.

@migbot @shazm I'll let you guys decide who will fix the issue or if it's a separate PR. I'll go ahead and approve the PR based on running the current test suite. I already created jira tickets to create e2e for errors/warnings once this is merged.

2021-03-22 21:49 UTC, josephbaylon approved these changes
LGTM. iOS e2e passed locally

2021-03-23 23:57 UTC, enahum approved these changes
I guess the table in the readme needs to be updated with Android as well, right now it is entirely ios focused

2021-03-24 03:07 UTC, merged