[MM-34374] [MM-34420] Various fixes
mattermost/react-native-network-client pull request #58
Opened 2021-03-31 03:17 UTC by migbot

#### Summary
* Adds `trustSelfSignedServerCertificate` to the WebSocketClient configuration.
* Uses `host` as the `kSecAttrLabel` for identity/certificate Keychain items. This allows both the APIClient and WebSocketClient to retrieve the correct certificate when their `host` values match. If a P12 has already been imported, further import attempts will trigger a client error event but the certificate will be found for the handshake and requests will be authenticated.
* Registered the client error callback prior to making the native function call so that any error events will be handled.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34374
https://mattermost.atlassian.net/browse/MM-34420

2021-03-31 06:49 UTC, josephbaylon requested changes
@migbot I'm getting the following when trying to build ios example app

![Screen Shot 2021-03-30 at 11 48 09 PM](https://user-images.githubusercontent.com/487991/113102140-79498680-91b2-11eb-8d5c-0a9c5fa5d1e0.png)

2021-03-31 18:19 UTC, josephbaylon commented
Changes copied to https://github.com/mattermost/react-native-network-client/pull/57 and should be testable there

2021-04-01 01:29 UTC, josephbaylon commented
@migbot For last commit, please revert the rejection for `APIClient.swift` so tests can pass, only websocket should have the rejection

2021-04-01 18:26 UTC, enahum commented
> > @migbot For last commit, please revert the rejection for `APIClient.swift` so tests can pass, only websocket should have the rejection
> 
> 
> 
> Hey Joseph, as mentioned in our chat, there are two cases in which the APIClient can import a P12. The first is when creating the APIClient. In this case we do not reject the promise as we don't want to prevent creation of the client if there's an error importing the P12 (ie, incorrect password). In this case the native side just sends an error event. Once the APIClient is created, the second case, client function `importClientP12`, is available for the client to retry the import. Since this function deals solely with importing the P12, we reject here if there is an error.
> 
> 
> 
> For the WebSocketClient, there's a limitation in that creating the client is coupled with P12 import since it needs to be passed down to the underlying Starscream library. For this reason we 1) don't provide a separate `importClientP12` function and 2) we reject if there is an import error during creation of the client.

I've got lost here... this is what I would expect

1. Create an API client
2. Attach or import a cert
3. Create a WS client
4. Connect the WS -> this uses the cert imported in step 2

Does that work?

2021-04-01 19:12 UTC, josephbaylon commented
@enahum The WS client is working fine and the restriction to not be able to import P12 once the WS client is created is in place. The rejection on WebSocketClient is then reasonable since there's no way for user to import new P12.

The issue is on the API client where we're allowing import of p12 once client has been created.

We have a `clientErrorEventHandler` that can be enabled/disabled in the preset API clients but always enabled when creating API client from the UI.

@migbot's concern, I believe, was that when p12 is invalid or has incorrect password that it wouldn't prompt the user with client error, that's why he added the rejection on the `APIClient`. But it does on both API client creation and when import to existing API client.

My original suggestion is to only apply the rejection on WebSocketClient but NOT to APIClient as doing it on APIClient would cause unnecessary promise rejection on cases where p12 has already been imported BUT the `clientErrorEventHandler` has been disabled, for reasons that we're not testing the error in those cases and the tests need to be idempotent.

We will add tests around the actual errors later when `clientErrorEventHandler` is enabled, but that's a separate concern.

2021-04-01 19:14 UTC, josephbaylon commented
Thus, I think the change in `APIClientImportP12Screen` is unnecessary and the rejection on `APIClient` needs to be reverted

2021-04-01 19:38 UTC, josephbaylon commented
@migbot Thanks for the update. We need to remove the navigate.back() so that whether or not the user receives an error, he's not automatically navigated back in terms of tests that don't care if the import was successful or not

2021-04-01 19:44 UTC, josephbaylon approved these changes
LGTM. I applied the changes in pr-57 and works there. However, I had to remove the navigate.back() in my PR to adjust to workflow for either successful/failed import

2021-04-01 22:43 UTC, josephbaylon approved these changes

2021-04-06 18:12 UTC, josephbaylon commented
@migbot I'll re-approve once you've pushed the fixes for retry and error codes. Thanks

2021-04-06 19:56 UTC, enahum approved these changes

2021-04-06 19:56 UTC, enahum commented on ios/WebSocketManager.swift
> +                    // do nothing
💯

2021-04-06 21:42 UTC, enahum approved these changes

2021-04-06 21:48 UTC, josephbaylon approved these changes
LGTM. Copied changes to PR-57 and tested and linear and exponential retry works and failure/success response goes to response overlay.

2021-04-06 21:49 UTC, merged